### ISSUE TITLE
执行pytorch2onnx.py时报错

### ISSUE THREAD

**Issue by hhhhhhogan** [polarisZhao/PFLD-pytorch#51]
您好，我在执行pytorch2onnx.py这个文件的时候报错：
====> check onnx model...
====> Simplifying...
Traceback (most recent call last):
  File "pytorch2onnx.py", line 46, in <module>
    onnx.save(model_opt, args.onnx_model_sim)
  File "C:\Users\Administrator\anaconda3\envs\py37\lib\site-packages\onnx\__init__.py", line 184, in save_model
    proto = write_external_data_tensors(proto, basepath)
  File "C:\Users\Administrator\anaconda3\envs\py37\lib\site-packages\onnx\external_data_helper.py", line 225, in write_external_data_tensors
    for tensor in _get_all_tensors(model):
  File "C:\Users\Administrator\anaconda3\envs\py37\lib\site-packages\onnx\external_data_helper.py", line 170, in _get_initializer_tensors
    for initializer in onnx_model_proto.graph.initializer:
AttributeError: 'tuple' object has no attribute 'graph'
问题应该是Simplifying的时候出错了，应该怎么解决呢？

**Comment by chenchangquan5** [comment]
代码：
    model_opt = onnxsim.simplify(args.onnx_model)
修改成如下：
    model_opt, check = onnxsim.simplify(args.onnx_model)
即可解决
